[workspace]
resolver = "2"
members = [ "apps/core/src-tauri", "crates/*", "drive"]

[workspace.package]
edition = "2021"
version = "0.0.1"
repository = "https://github.com/centlax/drive"


[workspace.dependencies]
